# Generated by Django 2.2.5 on 2019-09-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_userevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='seats',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
