# Generated by Django 2.2.5 on 2019-09-08 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_userevent_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='event',
        ),
        migrations.AddField(
            model_name='userevent',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
