# Generated by Django 2.2.5 on 2019-09-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20190911_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_image',
            new_name='image',
        ),
    ]
